// Code generated by protoc-gen-go.
// source: transport.proto
// DO NOT EDIT!

/*
Package transport is a generated protocol buffer package.

It is generated from these files:
	transport.proto

It has these top-level messages:
*/
package transport

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ActionType int32

const (
	ActionType_unknown   ActionType = 0
	ActionType_login_req ActionType = 1
	ActionType_login_rsp ActionType = 2
)

var ActionType_name = map[int32]string{
	0: "unknown",
	1: "login_req",
	2: "login_rsp",
}
var ActionType_value = map[string]int32{
	"unknown":   0,
	"login_req": 1,
	"login_rsp": 2,
}

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}
func (x ActionType) String() string {
	return proto.EnumName(ActionType_name, int32(x))
}
func (x *ActionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ActionType_value, data, "ActionType")
	if err != nil {
		return err
	}
	*x = ActionType(value)
	return nil
}

func init() {
	proto.RegisterEnum("transport.ActionType", ActionType_name, ActionType_value)
}
